version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - run:
          name: install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: install gcc and g++ compilers
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: install wget
          command: 'apt-get update && sudo apt-get install -y wget'
      - run:
          name: install make
          command: 'apt-get update && sudo apt-get install -y make'
      - run:
          name: download cmake 3.19
          command: 'cd / && wget "https://github.com/Kitware/CMake/releases/download/v3.19.0-rc1/cmake-3.19.0-rc1-Linux-x86_64.sh"'
      - run:
          name: install cmake 3.19
          command: 'cd / && chmod +x cmake-3.19.0-rc1-Linux-x86_64.sh && ./cmake-3.19.0-rc1-Linux-x86_64.sh --skip-license'
      - run:
          name: install lcov
          command: 'apt-get update && sudo apt-get install -y lcov'
      - run:
          name: install git
          command: 'apt-get update && sudo apt-get install -y git'
      - run:
          name: go to project folder
          command: 'cd /root/project'
      - checkout
      - run:
          name: initialising submodules
          command: 'git submodule init && git submodule update --remote'
      - run:
          name: creating production build files and binaries
          command: './build.sh'
      - run:
          name: running tests
          command: './run_tests.sh'
      - run:
          name: generating test coverage report
          command: './generate_coverage.sh'
      - store_artifacts:
          path: test-coverage
